app = "constructify-dev"
primary_region = "sjc"

[env]
  BIND = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
